//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Commande
    {
        public int Num_commande { get; set; }
        public Nullable<int> num_etudiant { get; set; }
        public Nullable<System.DateTime> datecommande { get; set; }
        public string destinataire { get; set; }
        public string ville_livraison { get; set; }
        public string pays_livraison { get; set; }
        public string adresse_livraison { get; set; }
        public Nullable<int> code_postal_livraison { get; set; }
        public string date_envoi { get; set; }
    
        public virtual Etudiant Etudiant { get; set; }
    }
}
