//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoUser
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string confirmEmail { get; set; }
        public string Name { get; set; }
        public string websiteurl { get; set; }
        public string password { get; set; }
        public string confirmpassword { get; set; }
        public string telephone { get; set; }
        public string Adresse { get; set; }
    }
}
