//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Manage_BooksEntities : DbContext
    {
        public Manage_BooksEntities()
            : base("name=Manage_BooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Auteur> Auteur { get; set; }
        public virtual DbSet<Authentification> Authentification { get; set; }
        public virtual DbSet<Editeur> Editeur { get; set; }
        public virtual DbSet<Etudiant> Etudiant { get; set; }
        public virtual DbSet<Exemplaire> Exemplaire { get; set; }
        public virtual DbSet<Mise_a_Jour> Mise_a_Jour { get; set; }
        public virtual DbSet<Ouvrage> Ouvrage { get; set; }
        public virtual DbSet<Type> Type { get; set; }
        public virtual DbSet<Version_ouvrage> Version_ouvrage { get; set; }
        public virtual DbSet<Commande> Commande { get; set; }
        public virtual DbSet<Formation> Formation { get; set; }
        public virtual DbSet<InfoUser> InfoUser { get; set; }
        public virtual DbSet<professour> professour { get; set; }
    }
}
