//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Manage_BooksEntities : DbContext
    {
        public Manage_BooksEntities()
            : base("name=Manage_BooksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Acheter> Acheters { get; set; }
        public virtual DbSet<appartient> appartients { get; set; }
        public virtual DbSet<Auteur> Auteurs { get; set; }
        public virtual DbSet<Authentification> Authentifications { get; set; }
        public virtual DbSet<Commander> Commanders { get; set; }
        public virtual DbSet<Editeur> Editeurs { get; set; }
        public virtual DbSet<Editeur1> Editeurs1 { get; set; }
        public virtual DbSet<Etudiant> Etudiants { get; set; }
        public virtual DbSet<Exemplaire> Exemplaires { get; set; }
        public virtual DbSet<Formation> Formations { get; set; }
        public virtual DbSet<InfoUser> InfoUsers { get; set; }
        public virtual DbSet<Inscription> Inscriptions { get; set; }
        public virtual DbSet<Mise_a_Jour> Mise_a_Jour { get; set; }
        public virtual DbSet<Ouvrage> Ouvrages { get; set; }
        public virtual DbSet<Ouvrage1> Ouvrages1 { get; set; }
        public virtual DbSet<professour> professours { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Type> Types { get; set; }
        public virtual DbSet<Version_ouvrage> Version_ouvrage { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
    }
}
