//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrage1
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ouvrage1()
        {
            this.appartients = new HashSet<appartient>();
            this.Exemplaires = new HashSet<Exemplaire>();
            this.Mise_a_Jour = new HashSet<Mise_a_Jour>();
            this.Auteurs = new HashSet<Auteur>();
        }
    
        public int id_ouvrage { get; set; }
        public string titre { get; set; }
        public Nullable<int> nb_pages { get; set; }
        public Nullable<int> id_Editeur { get; set; }
        public Nullable<int> Quantite { get; set; }
        public string Type { get; set; }
        public Nullable<int> id_Auteur { get; set; }
        public string Photo { get; set; }
        public Nullable<int> id_type { get; set; }
        public string libelle { get; set; }
        public string nomE { get; set; }
        public string prenomE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appartient> appartients { get; set; }
        public virtual Auteur Auteur { get; set; }
        public virtual Editeur1 Editeur { get; set; }
        public virtual Editeur1 Editeur1 { get; set; }
        public virtual Editeur1 Editeur2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exemplaire> Exemplaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mise_a_Jour> Mise_a_Jour { get; set; }
        public virtual Ouvrage1 Ouvrages1 { get; set; }
        public virtual Ouvrage1 Ouvrage { get; set; }
        public virtual Type Type1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auteur> Auteurs { get; set; }
    }
}
