//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class professour
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public professour()
        {
            this.Formations = new HashSet<Formation>();
        }
    
        public int id_prof { get; set; }
        public string Nom { get; set; }
        public string prenom { get; set; }
        public Nullable<System.DateTime> datenaissance { get; set; }
        public string email { get; set; }
        public string adresse { get; set; }
        public string domaine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Formation> Formations { get; set; }
    }
}
