//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Admin_pro.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int id_reservation { get; set; }
        public Nullable<int> quantite { get; set; }
        public string description { get; set; }
        public Nullable<System.DateTime> datereservation { get; set; }
        public Nullable<int> id_ouvrage { get; set; }
        public Nullable<System.DateTime> date_envoi { get; set; }
        public string Type { get; set; }
    
        public virtual Ouvrage Ouvrage { get; set; }
    }
}
