//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_And_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class appartients
    {
        public int id_ouvrage { get; set; }
        public string id_type { get; set; }
    
        public virtual Ouvrages Ouvrages { get; set; }
    }
}
