//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_And_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editeur
    {
        public int id_Editeur { get; set; }
        public string ville { get; set; }
        public string Email { get; set; }
        public string nomE { get; set; }
        public string prenomE { get; set; }
        public string nationalite { get; set; }
    }
}
