//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_And_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exemplaires
    {
        public int num_exemplaire { get; set; }
        public string titre { get; set; }
        public Nullable<int> nb_pages { get; set; }
        public Nullable<int> num_etudiant { get; set; }
        public Nullable<int> id_ouvrage { get; set; }
        public string Categorie { get; set; }
    
        public virtual Etudiants Etudiants { get; set; }
        public virtual Ouvrages Ouvrages { get; set; }
    }
}
