//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_And_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InfoUsers
    {
        public int id { get; set; }
        public string Email { get; set; }
        public string Prenom { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> DateCreation { get; set; }
        public string password { get; set; }
        public string telephone { get; set; }
        public string Adresse { get; set; }
        public string Confirmpassword { get; set; }
        public string Photo { get; set; }
        public string User_Name { get; set; }
    }
}
