//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_And_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrages
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ouvrages()
        {
            this.appartients = new HashSet<appartients>();
            this.Exemplaires = new HashSet<Exemplaires>();
            this.Mise_a_Jour = new HashSet<Mise_a_Jour>();
            this.Auteurs1 = new HashSet<Auteurs>();
        }
    
        public int id_ouvrage { get; set; }
        public string titre { get; set; }
        public Nullable<int> nb_pages { get; set; }
        public Nullable<int> id_Editeur { get; set; }
        public Nullable<int> Quantite { get; set; }
        public string Type { get; set; }
        public Nullable<int> id_Auteur { get; set; }
        public string Photo { get; set; }
        public Nullable<int> id_type { get; set; }
        public string libelle { get; set; }
        public string nomE { get; set; }
        public string prenomE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<appartients> appartients { get; set; }
        public virtual Auteurs Auteurs { get; set; }
        public virtual Editeurs Editeurs { get; set; }
        public virtual Editeurs Editeurs1 { get; set; }
        public virtual Editeurs Editeurs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Exemplaires> Exemplaires { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Mise_a_Jour> Mise_a_Jour { get; set; }
        public virtual Ouvrages Ouvrages1 { get; set; }
        public virtual Ouvrages Ouvrages2 { get; set; }
        public virtual Types Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Auteurs> Auteurs1 { get; set; }
    }
}
