//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Library_And_Education.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ouvrage
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ouvrage()
        {
            this.Commander = new HashSet<Commander>();
        }
    
        public int id_ouvrage { get; set; }
        public string titre { get; set; }
        public Nullable<int> nb_pages { get; set; }
        public Nullable<int> id_Editeur { get; set; }
        public Nullable<int> Quantite { get; set; }
        public string Type { get; set; }
        public Nullable<int> id_Auteur { get; set; }
        public string Photo { get; set; }
        public Nullable<int> id_type { get; set; }
        public string libelle { get; set; }
        public string prenomE { get; set; }
        public string nomE { get; set; }
        public Nullable<double> Prix { get; set; }
        public string Description { get; set; }
        public Nullable<double> Total { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Commander> Commander { get; set; }
    }
}
